config/routes.rb
Rails.application.routes.draw do
  resources :pets # create pets resource RESTful urls
  root 'pets#index' # set root route
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  validates :name, presence: true
  validates :description, length: {minimum: 10}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @pets = Pet.all
  end

  def show
    # check rails routes
    # pets#show requires :id params
    @pet = Pet.find(params[:id])
  end

  def new
    @pet = Pet.new
  end

  def create
    # param returns ActionController::Parameters object
    # represents the fields coming in from the forms
    # :pet --> has attributes that we are interested in
    # due to built-in security features of rails, you must specify which param to permit
    # and they are name, age and description in this case
    @pet = Pet.new(pet_params)
    if @pet.save
      # redict to the pets#show
      # same as rediect_to pet_path(@pet)
      redirect_to @pet
    else
      # return the user back to the creation form.
      render 'new'
    end
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    
    if @pet.update(pet_params)
      redirect_to @pet
    else
      render 'edit'
    end
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy

    redirect_to pets_path
  end

  private
    def pet_params
      params.require(:pet).permit(:name, :age, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/hello/index.html.erb
<h1>Hello World on Rails!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<%= form_with model: @pet, local: true do |form| %>
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@pet.errors.count, "error") %> prohibited
        this pet from being saved:
      </h2>
      <ul>
        <% @pet.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :age %><br>
    <%= form.text_area :age %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/pets/edit.html.erb
<h1>Edit Pet</h1>
<%= render 'form' %>

app/views/pets/index.html.erb
<table>
  <tr>
    <th colspan="5"></th>
  </tr>
  <% @pets.each do |p| %>
    <tr>
        <td><%= link_to p.name, pet_path(p)  %></td>
        <td><%= link_to 'Edit', edit_pet_path(p) %></td>
        <td><%= link_to 'Remove', pet_path(p), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'New pet', new_pet_path  %>
<%# new_pet_path is the route set to pets#new %>

app/views/pets/new.html.erb
<h1>New Pet</h1>
<%= render 'form' %>

app/views/pets/show.html.erb
<%# @pet is from the pets_controller.rb %>
<p>
  <strong>Name:</strong>
  <%= @pet.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @pet.age %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pet.description %>
</p>

<%= link_to 'Home', pets_path %>
<%= link_to 'Edit', edit_pet_path %>
<%= link_to 'Remove', @pet, method: :delete, data: { confirm: 'Are you sure?' } %>